# Configure Jenkins Job DSL with Docker Integration
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with Docker integration
      jenkins_job:
        config: "{{ lookup('template', 'docker_integration_job.xml.j2') }}"
        name: docker_integration_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"