# Configure Jenkins Job DSL with GitHub SCM
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with GitHub SCM
      jenkins_job:
        config: "{{ lookup('template', 'github_scm_job.xml.j2') }}"
        name: github_scm_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"