# Configure Jenkins Job DSL with Multiple SCM
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with multiple SCM
      jenkins_job:
        config: "{{ lookup('template', 'multiple_scm_job.xml.j2') }}"
        name: multiple_scm_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"