# Configure Jenkins Pipeline with Maven
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins pipeline with Maven
      jenkins_pipeline:
        name: maven_pipeline
        state: present
        config: "{{ lookup('template', 'maven_pipeline.groovy.j2') }}"
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"