# Configure Jenkins Pipeline with Docker Push
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins pipeline with Docker push
      jenkins_pipeline:
        name: docker_push_pipeline
        state: present
        config: "{{ lookup('template', 'docker_push_pipeline.groovy.j2') }}"
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"