# Configure Jenkins Pipeline with Parallel Stages
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins pipeline with parallel stages
      jenkins_pipeline:
        name: parallel_stages_pipeline
        state: present
        config: "{{ lookup('template', 'parallel_stages_pipeline.groovy.j2') }}"
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"