# Configure Jenkins Pipeline with Input Step
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins pipeline with input step
      jenkins_pipeline:
        name: input_step_pipeline
        state: present
        config: "{{ lookup('template', 'input_step_pipeline.groovy.j2') }}"
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"