# Configure Jenkins Pipeline with Retry
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins pipeline with retry
      jenkins_pipeline:
        name: retry_pipeline
        state: present
        config: "{{ lookup('template', 'retry_pipeline.groovy.j2') }}"
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"