# Configure Jenkins Pipeline with Artifacts
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins pipeline with artifacts
      jenkins_pipeline:
        name: artifacts_pipeline
        state: present
        config: "{{ lookup('template', 'artifacts_pipeline.groovy.j2') }}"
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"