# Configure Jenkins Job
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins job
      jenkins_job:
        config: "{{ lookup('template', 'job.xml.j2') }}"
        name: my_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"
