# Configure Docker Compose
---
- hosts: dockerservers
  become: yes
  tasks:
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    - name: Deploy Docker Compose file
      docker_compose:
        project_src: /path/to/docker-compose/project
        state: present
