# Configure Kubernetes Cluster
---
- hosts: kubemasters
  become: yes
  tasks:
    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
    - name: Initialize Kubernetes master
      command: kubeadm init
