# Configure NGINX

---
- hosts: webservers
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes
