# Configure RabbitMQ
---
- hosts: rabbitmqnodes
  become: yes
  tasks:
    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
    - name: Start RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
