# Configure Django Application
---
- hosts: djangoservers
  become: yes
  tasks:
    - name: Install Python and Django
      apt:
        name: 
          - python3
          - python3-pip
      state: present
    - name: Install Django
      pip:
        name: Django
        state: present
    - name: Deploy Django Application
      template:
        src: django_settings.py.j2
        dest: /path/to/django/app/settings.py