# Configure Jenkins Job DSL Seed Job
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL seed job
      jenkins_job:
        config: "{{ lookup('template', 'seed_job.xml.j2') }}"
        name: seed_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"
