# Configure Vault for Dynamic Secrets
---
- hosts: vaultservers
  become: yes
  tasks:
    - name: Enable database secrets engine
      shell: "vault secrets enable database"
    - name: Configure PostgreSQL secrets engine
      shell: "vault write database/config/mydb plugin_name=postgresql-database-plugin allowed_roles=myrole connection_url='postgresql://{{ db_user }}:{{ db_password }}@{{ db_host }}:5432/{{ db_name }}?sslmode=disable'"
    - name: Create role in PostgreSQL secrets engine
      shell: "vault write database/roles/myrole db_name=mydb creation_statements='CREATE ROLE \"{{ name }}\" WITH LOGIN PASSWORD '{{ password }}' VALID UNTIL '{{ expiration }}'; GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"{{ name }}\";'"
