#Configure Jenkins Pipeline with Docker
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins pipeline with Docker
      jenkins_pipeline:
        name: my_docker_pipeline
        state: present
        config: "{{ lookup('template', 'docker_pipeline.groovy.j2') }}"
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"
