# Configure Vault SSH Secrets Engine
---
- hosts: vaultservers
  become: yes
  tasks:
    - name: Enable SSH secrets engine
      shell: "vault secrets enable ssh"
    - name: Configure SSH secrets engine
      shell: "vault write ssh/roles/myrole key_type=otp default_user=ubuntu"