#Configure Jenkins Job with Parameters
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins job with parameters
      jenkins_job:
        config: "{{ lookup('template', 'parameterized_job.xml.j2') }}"
        name: parameterized_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"