# Configure Jenkins Job DSL Seed Job with Parameters
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL seed job with parameters
      jenkins_job:
        config: "{{ lookup('template', 'seed_job_with_parameters.xml.j2') }}"
        name: seed_job_with_parameters
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"