# Configure Jenkins Job DSL Build Wrapper
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with build wrapper
      jenkins_job:
        config: "{{ lookup('template', 'build_wrapper_job.xml.j2') }}"
        name: build_wrapper_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"