# Configure Jenkins Job DSL with Git SCM
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with Git SCM
      jenkins_job:
        config: "{{ lookup('template', 'git_scm_job.xml.j2') }}"
        name: git_scm_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"