# Configure Jenkins Job DSL Triggers
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with triggers
      jenkins_job:
        config: "{{ lookup('template', 'triggers_job.xml.j2') }}"
        name: triggers_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"