# Configure Jenkins Job DSL Custom Workspace
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with custom workspace
      jenkins_job:
        config: "{{ lookup('template', 'custom_workspace_job.xml.j2') }}"
        name: custom_workspace_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"