# Configure Jenkins Job DSL with Maven Integration
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with Maven integration
      jenkins_job:
        config: "{{ lookup('template', 'maven_job.xml.j2') }}"
        name: maven_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"