# Configure Jenkins Job DSL Parameterized Build
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL parameterized build job
      jenkins_job:
        config: "{{ lookup('template', 'parameterized_build_job.xml.j2') }}"
        name: parameterized_build_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"