# Configure Jenkins Job DSL with Gradle Build
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with Gradle build
      jenkins_job:
        config: "{{ lookup('template', 'gradle_build_job.xml.j2') }}"
        name: gradle_build_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"