# Configure Jenkins Job DSL Matrix Project
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL matrix project
      jenkins_job:
        config: "{{ lookup('template', 'matrix_project_job.xml.j2') }}"
        name: matrix_project_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"