#Configure Jenkins Job DSL Poll SCM
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with Poll SCM
      jenkins_job:
        config: "{{ lookup('template', 'poll_scm_job.xml.j2') }}"
        name: poll_scm_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"
