# Configure Jenkins Job DSL Pipeline Script:
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL pipeline script job
      jenkins_job:
        config: "{{ lookup('template', 'pipeline_script_job.xml.j2') }}"
        name: pipeline_script_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"