# Configure Jenkins Job DSL Artifacts Archiving
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with artifacts archiving
      jenkins_job:
        config: "{{ lookup('template', 'artifacts_archiving_job.xml.j2') }}"
        name: artifacts_archiving_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"