# Configure Jenkins Job DSL Retry Build
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with retry build
      jenkins_job:
        config: "{{ lookup('template', 'retry_build_job.xml.j2') }}"
        name: retry_build_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"                           