# Configure Jenkins Job DSL Parameterized Trigger
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with parameterized trigger
      jenkins_job:
        config: "{{ lookup('template', 'parameterized_trigger_job.xml.j2') }}"
        name: parameterized_trigger_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"
