#Configure Jenkins Job DSL Groovy Postbuild
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with Groovy postbuild
      jenkins_job:
        config: "{{ lookup('template', 'groovy_postbuild_job.xml.j2') }}"
        name: groovy_postbuild_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"
