# Configure Jenkins Job DSL Docker Integration
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with dynamic extended choice parameter
      jenkins_job:
        config: "{{ lookup('template', 'dynamic_extended_choice_job.xml.j2') }}"
        name: dynamic_extended_choice_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"
