# Configure Jenkins Job DSL Conditional Build Step
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with conditional build step
      jenkins_job:
        config: "{{ lookup('template', 'conditional_build_step_job.xml.j2') }}"
        name: conditional_build_step_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"