# Configure Jenkins Job DSL with Artifactory Integration
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Create Jenkins DSL job with Artifactory integration
      jenkins_job:
        config: "{{ lookup('template', 'artifactory_integration_job.xml.j2') }}"
        name: artifactory_integration_job
        state: present
    - name: Reload Jenkins configuration
      jenkins_script:
        script: "Jenkins.instance.reload()"