# Deploy a Python Flask Application with uWSGI
---
- hosts: python_servers
  become: yes
  tasks:
    - name: Install Python and uWSGI
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - uwsgi
    - name: Copy and install Flask application
      pip:
        requirements: /path/to/local/flask/app/requirements.txt
    - name: Configure and start uWSGI
      command: uwsgi --ini /path/to/local/flask/app/uwsgi.ini