# Deploy a Vue.js Application
---
- hosts: node_servers
  become: yes
  tasks:
    - name: Install Node.js and npm
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
    - name: Copy and install Vue.js application
      npm:
        path: /path/to/local/vuejs/app
        state: present
    - name: Build the Vue.js application
      command: npm run build --prefix /path/to/local/vuejs/app
    - name: Deploy the Vue.js application
      copy:
        src: /path/to/local/vuejs/app/dist
        dest: /var/www/html/vuejs