# Deploy a Next.js Application
---
- hosts: node_servers
  become: yes
  tasks:
    - name: Install Node.js and npm
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
    - name: Copy and install Next.js application
      npm:
        path: /path/to/local/nextjs/app
        state: present
    - name: Build and start the Next.js application
      command: npm run build --prefix /path/to/local/nextjs/app && npm start --prefix /path/to/local/nextjs/app