# Deploy a FastAPI Web App
---
- hosts: python_servers
  become: yes
  tasks:
    - name: Install Python and FastAPI
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
    - name: Copy and install FastAPI app
      pip:
        requirements: /path/to/local/fastapi/app/requirements.txt
    - name: Start FastAPI app
      command: uvicorn app:app --host 0.0.0.0 --port 8000