# Deploy a Flask-SocketIO Real-Time App
---
- hosts: python_servers
  become: yes
  tasks:
    - name: Install Python and Flask-SocketIO
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
    - name: Copy and install Flask-SocketIO app
      pip:
        requirements: /path/to/local/flask/socketio/app/requirements.txt
    - name: Start Flask-SocketIO app
      command: python /path/to/local/flask/socketio/app/app.py