# Deploy a Jupyter Notebook Server
---
- hosts: python_servers
  become: yes
  tasks:
    - name: Install Python and Jupyter Notebook
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
    - name: Install Jupyter Notebook
      pip:
        name: jupyter
    - name: Start Jupyter Notebook
      command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser