# Orchestrate HashiCorp Vault Secret Management
---
- hosts: vault_server
  become: yes
  tasks:
    - name: Configure Vault Secrets
      template:
        src: /path/to/local/vault/vault_secrets.hcl.j2
        dest: /etc/vault/vault_secrets.hcl
      notify:
        - restart vault
  handlers:
    - name: restart vault
      service:
        name: vault
        state: restarted