# Orchestrate Huawei Cloud ECS Deployment
---
- hosts: huawei_cloud_ecs_controller
  become: yes
  tasks:
    - name: Deploy Huawei Cloud ECS Instances
      huaweicloud_ecs:
        access_key: "{{ huawei_access_key }}"
        secret_key: "{{ huawei_secret_key }}"
        region: "{{ huawei_region }}"
        instance_name: "{{ item.instance_name }}"
        flavor: "{{ item.flavor }}"
        image: "{{ item.image }}"
        vpc_id: "{{ huawei_vpc_id }}"
        subnet_id: "{{ huawei_subnet_id }}"
        security_group_id: "{{ huawei_sg_id }}"
        count: "{{ item.count }}"
      with_items:
        - { instance_name: "web_instance", flavor: "ecs.flavor.small", image: "ecs.image.web", count: 2 }
        - { instance_name: "app_instance", flavor: "ecs.flavor.medium", image: "ecs.image.app", count: 3 }