# Orchestrate Splunk Indexer Cluster Configuration
---
- hosts: splunk_indexer_cluster
  become: yes
  tasks:
    - name: Configure Splunk Indexer Cluster
      splunk_indexer_cluster:
        master_uri: "{{ splunk_master_uri }}"
        master_username: "{{ splunk_master_username }}"
        master_password: "{{ splunk_master_password }}"
        replication_factor: "{{ item.replication_factor }}"
        search_factor: "{{ item.search_factor }}"
        cluster_label: "{{ item.cluster_label }}"
      with_items:
        - { replication_factor: 3, search_factor: 2, cluster_label: "web_cluster" }
        - { replication_factor: 4, search_factor: 3, cluster_label: "app_cluster" }