# Orchestrate Oracle Cloud Infrastructure (OCI) Load Balancer Configuration
---
- hosts: oci_lb_controller
  become: yes
  tasks:
    - name: Configure OCI Load Balancer
      oci_load_balancer:
        api_key: "{{ oci_api_key }}"
        tenancy_ocid: "{{ oci_tenancy_ocid }}"
        user_ocid: "{{ oci_user_ocid }}"
        fingerprint: "{{ oci_fingerprint }}"
        private_key_path: "{{ oci_private_key_path }}"
        region: "{{ oci_region }}"
        compartment_ocid: "{{ oci_compartment_ocid }}"
        display_name: "{{ item.lb_name }}"
        shape_name: "{{ item.shape_name }}"
        backend_sets:
          - name: "web_backend_set"
            policy: "ROUND_ROBIN"
            health_check:
              protocol: "HTTP"
              port: 80
              retries: 3
              timeout_in_millis: 3000
              interval_in_millis: 10000
            backends:
              - name: "web_server_1"
                ip_address: "10.0.1.5"
                port: 80
              - name: "web_server_2"
                ip_address: "10.0.1.6"
                port: 80
      with_items:
        - { lb_name: "web_lb", shape_name: "100Mbps", }
        - { lb_name: "app_lb", shape_name: "500Mbps", }