# Orchestrate Cisco ACI (Application Centric Infrastructure) Configuration
---
- hosts: cisco_aci_controller
  become: yes
  tasks:
    - name: Configure Cisco ACI
      aci_rest:
        hostname: "{{ cisco_aci_apic }}"
        username: "{{ cisco_aci_username }}"
        password: "{{ cisco_aci_password }}"
        validate_certs: no
        path: "{{ item.path }}"
        method: "{{ item.method }}"
        body: "{{ item.body }}"
        status_code: 200
      with_items:
        - { path: "api/mo/uni/tn-common/out-default/instP-default.json", method: "post", body: { "fvRsCons": { "tDn": "topology/pod-1/paths-102/pathep-[eth1/2]", "status": "created,modified" } } }
        - { path: "api/mo/uni/tn-common/out-default/instP-default.json", method: "post", body: { "fvRsCons": { "tDn": "topology/pod-1/paths-103/pathep-[eth1/2]", "status": "created,modified" } } }