# Orchestrate HashiCorp Vault Secret Engine Configuration
---
- hosts: vault_controller
  become: yes
  tasks:
    - name: Configure HashiCorp Vault Secret Engine
      vault_policy:
        name: "{{ item.policy_name }}"
        rules: "{{ item.policy_rules }}"
        state: present
      with_items:
        - { policy_name: "web_app_secrets", policy_rules: "path \"secret/web/*\" { capabilities = [\"read\"] }" }
        - { policy_name: "db_secrets", policy_rules: "path \"secret/db/*\" { capabilities = [\"read\"] }" }