# Deploy Jenkins CI/CD Server
---
- hosts: jenkins_server
  become: yes
  tasks:
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    - name: Configure Jenkins
      template:
        src: /path/to/local/jenkins/jenkins_config.xml.j2
        dest: /etc/jenkins/jenkins_config.xml
      notify:
        - restart jenkins
  handlers:
    - name: restart jenkins
      service:
        name: jenkins
        state: restarted