# Deploy Microsoft Azure Virtual Machines
---
- hosts: azure_vm
  become: yes
  tasks:
    - name: Install Azure CLI
      apt:
        name: azure-cli
        state: present
    - name: Configure Azure VMs
      template:
        src: /path/to/local/azure/azure_vm_config.json.j2
        dest: /etc/azure/azure_vm_config.json