# Update System Packages and Security Patches
---
- hosts: all
  become: yes
  tasks:
    - name: Update system packages
      package:
        name: "*"
        state: latest
      register: update_result
    - name: Check for updates
      debug:
        var: update_result