# Configure IPtables for Network Security
---
- hosts: all
  become: yes
  tasks:
    - name: Install iptables
      package:
        name: iptables
        state: present
    - name: Configure iptables
      template:
        src: "iptables.rules.j2"
        dest: "/etc/iptables.rules"
      notify: restart iptables