# Configure Encrypted Communications with VPN (OpenVPN)
---
- hosts: vpn_servers
  become: yes
  tasks:
    - name: Install OpenVPN
      package:
        name: openvpn
        state: present
    - name: Configure OpenVPN
      template:
        src: "openvpn_server.conf.j2"
        dest: "/etc/openvpn/server.conf"
      notify: restart openvpn