# Configure BIOS/UEFI Password
---
- hosts: all
  become: yes
  tasks:
    - name: Configure BIOS/UEFI password
      shell: "echo 'password' | sudo -S -k bash -c 'echo -e \"password\npassword\" | sudo passwd'"