# Set Password Policies
---
- hosts: all
  become: yes
  tasks:
    - name: Set password policies
      pam_password:
        name: "{{ item.name }}"
        minlen: "{{ item.minlen }}"
        maxrepeat: "{{ item.maxrepeat }}"
        minclass: "{{ item.minclass }}"
        maxclassrepeat: "{{ item.maxclassrepeat }}"
      with_items:
        - { name: "password-auth-ac", minlen: 10, maxrepeat: 3, minclass: 2, maxclassrepeat: 2 }