# Enable Two-Factor Authentication (2FA) for SSH
---
- hosts: all
  become: yes
  tasks:
    - name: Install libpam-google-authenticator
      package:
        name: libpam-google-authenticator
        state: present
    - name: Enable Two-Factor Authentication for SSH
      pam_d:
        name: sshd
        type: auth
        control_flag: requisite
        module_path: pam_google_authenticator.so
        module_arguments: "{{ item }}"
      with_items:
        - "nullok"