# Configure Sysctl Parameters for Kernel Hardening
---
- hosts: all
  become: yes
  tasks:
    - name: Set sysctl parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      with_items:
        - { name: "net.ipv4.ip_forward", value: 0 }
        - { name: "net.ipv4.conf.all.send_redirects", value: 0 }
        - { name: "net.ipv4.conf.default.send_redirects", value: 0 }