# Configure Strong Password Policies
---
- hosts: all
  become: yes
  tasks:
    - name: Configure strong password policies
      pam_pwquality:
        name: system-auth-ac
        minlen: 12
        minclass: 3
